[uwsgi]
module = wsgi:application
socket = :5000
chdir = /app

processes = 8
threads = 8
harakiri = 0
http-timeout = 0
idle = 0
socket-timeout = 120000
limit-post = 52428800
buffer-size = 65535
thunder-lock
lazy-apps = true
http-auto-chunked = true
http-keepalive = true
disable-write-exception = true
#worker-reload-mercy = 0

# import sys
# import logging
 
#sys.path.insert(0, '/var/www/flaskapp')
#sys.path.insert(0, '/var/www/flaskapp/venv/lib/python3.10/site-packages/')
 
# Set up logging
# logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)




